export const SET_CURRENT_USER_NULL = 'SET_CURRENT_USER_NULL';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';

export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';

export const ADD_ITEM_CART = 'ADD_ITEM_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const CLEAR_ITEM_CART = 'CLEAR_ITEM_CART';
export const CLEAR_ALL_ITEMS_FROM_CART = 'CLEAR_ALL_ITEMS_FROM_CART';

export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAIL = 'FETCH_COLLECTIONS_FAIL';

export const CLEAR_COLLECTIONS = 'CLEAR_COLLECTIONS';
